import Head from "next/head"; // Import the Head component from Next.js

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrelineScript from "./components/PrelineScript";
import Wrapper from "./components/Wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head> {/* Use the Head component to manage the <head> section */}
         <meta name="viewport"  content="width=device-width, initial-scale=1" /> 
      </Head>
      <body className={inter.className}>
        <Wrapper>
                  <PrelineScript />
        {children}
        </Wrapper>
        

      </body>
    </html>
  );
}
